version: '3.8'

networks:
    app: ~

services:
    app:
        build: .
        volumes:
            - .:/srv/app
            - ./.docker/app/php.ini:/usr/local/etc/php/php.ini
        networks:
            - app
        depends_on:
            - db
            - elasticsearch
            - mailhog

    nginx:
        image: nginx:alpine
        ports:
            - ${APP_PORT:-80}:80
        volumes:
            - .:/srv/app
            - ./.docker/nginx/app.conf:/etc/nginx/conf.d/app.conf
        networks:
            - app
        depends_on:
            - app

    db:
        image: postgres:14-alpine
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        volumes:
            - ./.docker/db/data:/var/lib/postgresql/data
        networks:
            - app

    elasticsearch:
        image: elasticsearch:7.17.1
        environment:
            - cluster.name=${ELASTIC_PORT:-app_cluster}
            - node.name=${ELASTIC_PORT:-app_node}
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms${ELASTIC_MEM} -Xmx${ELASTIC_MEM}"
            - cluster.initial_master_nodes=${ELASTIC_PORT:-app_node}
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - elasticsearch:/usr/share/elasticsearch/data
        networks:
            - app

    mailhog:
        image: 'mailhog/mailhog:latest'
        ports:
            - ${MAILHOG_PORT:-8025}:8025
        networks:
            - app

volumes:
    elasticsearch: ~
